# Generated by Django 4.1.6 on 2023-02-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='scrip_id',
            field=models.IntegerField(),
        ),
    ]
